### ISSUE TITLE
👩‍🔬 Investigate enrichment for raw flow data with context from SNMP to make it human-readable

### ISSUE THREAD

**Issue by mvrueden** [Riptide-Labs/riptide#16]
In the flow of raw data, the network interface is the internal SNMP ifindex as a number. As a user, you want to see the human-readable name for that particular interface to understand where the traffic happened. Unfortunately, we can't rely on a fixed ifIndex <-> ifName mapping. It can happen if you reboot a router and the mapping changes. To give the user some more context from his particular deployment, the ifAlias could also be interesting, cause this is a field a user can set manually to indicate what is connected on which port.

> “Each interface is identified by a unique value of the ifIndex object, and the description of ifIndex constrains its value as follows: Its value ranges between 1 and the value of ifNumber. The value for each interface must remain constant at least from one re-initialization of the entity's network management system to the next re-initialization."

So next re-initialization means the system reboots and it can change. Various vendors like Cisco allow you to persist the ifIndex to ensure they stay the same for the next re-initialization, but it's not the default and we can't rely on it.

See here: https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/28420-ifIndex-Persistence.html

Some examples show how the ifIndex is used to identify the ifName, ifAlias, and ifDescr. The ifIndex is used as the suffix to indicate the related corresponding data in the other tables.

![Screenshot 2023-10-31 at 09 24 07](https://github.com/PikkaLabs/riptide/assets/1095181/e1cf9ae3-f8d2-495b-8178-9771fc18dae1)

![Screenshot 2023-10-31 at 09 23 32](https://github.com/PikkaLabs/riptide/assets/1095181/fbdab436-bc67-476b-9ae4-3d845ca8a9ec)

![Screenshot 2023-10-31 at 09 23 47](https://github.com/PikkaLabs/riptide/assets/1095181/8af02443-b473-483a-8cea-a31770f273b3)

![Screenshot 2023-10-31 at 09 24 19](https://github.com/PikkaLabs/riptide/assets/1095181/8d647b22-1a37-494f-9a5f-bcc6a1e202d8)

**Comment by indigo423** [comment]
_(bearbeitet: Verweis auf das Konfigurations-Repository eines externen Anbieters entfernt)_
